[ADDITIONAL_OPTIONS.bool_opt]
desc = "A boolean option"
value = true
type = "bool"

[ADDITIONAL_OPTIONS.int_opt]
desc = "An integer option"
value = 42
type = "int"

[ADDITIONAL_OPTIONS.float_opt]
desc = "A float option"
value = 3.14
type = "float"

[ADDITIONAL_OPTIONS.string_opt]
desc = "A string option"
value = "Hello World"
type = "string"

[ADDITIONAL_OPTIONS.list_opt]
desc = "A list option"
value = ["Hello", "World"]
type = "list"

[ADDITIONAL_OPTIONS.text_opt]
desc = "A text option"
value = """Hello
World"""
type = "text"

[ADDITIONAL_OPTIONS.auto_opt]
desc = "An auto option"
value = {}
type = "auto"

[ADDITIONAL_OPTIONS.ns_opt]
desc = "A namespace option"
type = "namespace"

[ADDITIONAL_OPTIONS.ns_opt.value.nest_opt]
desc = "A nested ns option"
type = "namespace"

[ADDITIONAL_OPTIONS.ns_opt.value.nest_opt.value.x]
desc = "An option of a nested ns option"
value = 1
itype = "int"
type = "choice"
choices = [1, 2, 3]
choices_desc = ["One", "Two", "Three"]

[ADDITIONAL_OPTIONS.ns_opt.value.y]
desc = "Another option of a ns option"
order = -1
value = [1.0, 2.0, 3.0]
itype = "float"
type = "mchoices"
choices = [1.0, 2.0, 3.0, 4.0, 5.0]
choices_desc = ["One", "Two", "Three", "Four", "Five"]

[RUNNING_OPTIONS.Local]
desc = "The options for running the pipeline locally"
command = "python -m pipeline @${configfile} --datadir ${datadir}"

[RUNNING_OPTIONS.Local.value.configfile]
desc = "The configuration file for the pipeline, typically generated by this wizard\n"
required = true
value = "config.toml"
placeholder = "config.toml"

[RUNNING_OPTIONS.Local.value.datadir]
desc = "The directory where the data is stored"
required = true
value = ""
