desc = "An example pipeline showing how pipen-cli-config works."
error_strategy = "ignore"
loglevel = "info"
name = "ExamplePipeline"
plugin_opts = { }
scheduler_opts = { }
auto_opt = { }
bool_opt = true
float_opt = 3.14
int_opt = 42
list_opt = [ "Hello", "World" ]
string_opt = "Hello World"
text_opt = """
Hello
World"""

[ns_opt]
y = [ 1, 2, 3 ]

  [ns_opt.nest_opt]
  x = 1

[P2.envs]
abc = "123"

  [P2.envs.method]
  a = 1
